# Generated by Django 5.0.5 on 2024-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('linkedln', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=150)),
                ('localizacao', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciasProfissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricaoresumo', models.TextField()),
                ('itemresumo', models.CharField(blank=True, max_length=150)),
                ('formacao', models.CharField(blank=True, max_length=150)),
                ('anoinicioeducacao', models.CharField(max_length=30)),
                ('anoterminoeducacao', models.CharField(max_length=30)),
                ('instituicao', models.CharField(blank=True, max_length=150)),
                ('descricaoeducacao', models.TextField(blank=True)),
                ('nomexp', models.CharField(max_length=150)),
                ('anoinicioxp', models.CharField(max_length=30)),
                ('anoterminoxp', models.CharField(max_length=30)),
                ('localidade', models.CharField(max_length=150)),
                ('item1', models.TextField(blank=True)),
                ('item2', models.TextField(blank=True)),
                ('item3', models.TextField(blank=True)),
                ('item4', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='perfil')),
                ('nome', models.CharField(max_length=150)),
                ('linkwhatsapp', models.URLField(blank=True, max_length=150)),
                ('linkgithub', models.URLField(blank=True, max_length=150)),
                ('linkinstagram', models.URLField(blank=True, max_length=150)),
                ('linklinkedin', models.URLField(blank=True, max_length=150)),
                ('imagemdefundo', models.ImageField(blank=True, upload_to='perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='projetos')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SobreMim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='sobremim')),
                ('descricao', models.TextField(blank=True)),
                ('funcao', models.CharField(blank=True, max_length=150)),
                ('descricaofuncao', models.TextField(blank=True)),
                ('item', models.CharField(blank=True, max_length=100)),
                ('itemresposta', models.CharField(max_length=100)),
                ('textofinal', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TecnologiasDeDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('tecnologia', models.CharField(max_length=150)),
                ('valor', models.CharField(max_length=10)),
            ],
        ),
    ]
