# Generated by Django 5.0.5 on 2024-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='linklinkedin',
        ),
        migrations.AddField(
            model_name='perfil',
            name='linklinkedln',
            field=models.URLField(blank=True, max_length=150, verbose_name='Link do Linkedln'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.CharField(max_length=150, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='linkedln',
            field=models.CharField(max_length=150, verbose_name='Linkedln'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='localizacao',
            field=models.URLField(verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=150, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='anoinicioeducacao',
            field=models.CharField(max_length=30, verbose_name='Ano de início do curso'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='anoinicioxp',
            field=models.CharField(max_length=30, verbose_name='Ano de início da experiência'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='anoterminoeducacao',
            field=models.CharField(max_length=30, verbose_name='Ano de término do curso'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='anoterminoxp',
            field=models.CharField(max_length=30, verbose_name='Ano de término da experiência'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='descricaoeducacao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='descricaoresumo',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='formacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Formação'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='instituicao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='itemresumo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Item Resumo'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='localidade',
            field=models.CharField(max_length=150, verbose_name='Local do Trabalho'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='experienciasprofissionais',
            name='nomexp',
            field=models.CharField(max_length=150, verbose_name='Experiência'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(upload_to='perfil', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagemdefundo',
            field=models.ImageField(blank=True, upload_to='perfil', verbose_name='Foto de fundo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='linkgithub',
            field=models.URLField(blank=True, max_length=150, verbose_name='Link do Github'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='linkinstagram',
            field=models.URLField(blank=True, max_length=150, verbose_name='Link do Instagram'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='linkwhatsapp',
            field=models.URLField(blank=True, max_length=150, verbose_name='Link do Whatsapp'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='projetos', verbose_name='Foto de capa do projeto'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='tipo',
            field=models.CharField(max_length=30, verbose_name='Tipo do projeto'),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='descricaofuncao',
            field=models.TextField(blank=True, verbose_name='Descrição da função'),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='funcao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='sobremim', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='item',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='itemresposta',
            field=models.CharField(max_length=100, verbose_name='Resposta do item'),
        ),
        migrations.AlterField(
            model_name='sobremim',
            name='textofinal',
            field=models.TextField(verbose_name='Descrição final'),
        ),
        migrations.AlterField(
            model_name='tecnologiasdedominio',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tecnologiasdedominio',
            name='tecnologia',
            field=models.CharField(max_length=150, verbose_name='Tecnologia'),
        ),
        migrations.AlterField(
            model_name='tecnologiasdedominio',
            name='valor',
            field=models.CharField(max_length=10, verbose_name='Valor'),
        ),
    ]
