# Generated by Django 5.0.5 on 2024-05-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_perfil_imagemdefundo_remove_sobremim_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobremimitem',
            name='itens',
        ),
    ]
