# Generated by Django 5.0.5 on 2024-05-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_tecnologiasdedominio_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciasProfissionaisEducacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(blank=True, max_length=150, verbose_name='Formação')),
                ('anoinicioeducacao', models.CharField(max_length=30, verbose_name='Ano de início do curso')),
                ('anoterminoeducacao', models.CharField(max_length=30, verbose_name='Ano de término do curso')),
                ('instituicao', models.CharField(blank=True, max_length=150, verbose_name='Instituição')),
                ('descricaoeducacao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciasProfissionaisResumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricaoresumo', models.TextField(verbose_name='Descrição')),
                ('item', models.CharField(max_length=150, verbose_name='Item do resumo')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciasProfissionaisXp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomexp', models.CharField(max_length=150, verbose_name='Experiência')),
                ('anoinicioxp', models.CharField(max_length=30, verbose_name='Ano de início da experiência')),
                ('anoterminoxp', models.CharField(max_length=30, verbose_name='Ano de término da experiência')),
                ('localidade', models.CharField(max_length=150, verbose_name='Local do Trabalho')),
                ('item', models.TextField(blank=True, verbose_name='Item da experiência')),
            ],
        ),
        migrations.DeleteModel(
            name='ExperienciasProfissionais',
        ),
    ]
