# Generated by Django 5.0.5 on 2024-05-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_experienciasprofissionaiseducacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciasProfissionaisResumoItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciasProfissionaisXpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Experiência')),
            ],
        ),
        migrations.RemoveField(
            model_name='experienciasprofissionaisresumo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='experienciasprofissionaisxp',
            name='item',
        ),
    ]
