# Generated by Django 5.0.5 on 2024-05-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_educacao_experienciasprofissionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciasprofissionaisitens',
            name='xp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.experienciasprofissionais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumoitens',
            name='resumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.resumo'),
            preserve_default=False,
        ),
    ]
