# Generated by Django 5.0.5 on 2024-05-09 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_experienciasprofissionaisitens_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciasprofissionais',
            name='xp',
        ),
        migrations.RemoveField(
            model_name='resumo',
            name='resumo',
        ),
        migrations.CreateModel(
            name='ExperienciasProfissionaisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150, verbose_name='Descrição do Item')),
                ('resumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='apps.experienciasprofissionais')),
            ],
        ),
        migrations.CreateModel(
            name='ResumoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150, verbose_name='Descrição do Item')),
                ('resumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='apps.resumo')),
            ],
        ),
        migrations.DeleteModel(
            name='ExperienciasProfissionaisItens',
        ),
        migrations.DeleteModel(
            name='ResumoItens',
        ),
    ]
