# Generated by Django 5.0.5 on 2024-05-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_experienciasprofissionais_xp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumoitem',
            old_name='item',
            new_name='descricao',
        ),
    ]
