# Generated by Django 5.0.5 on 2024-05-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_rename_resumo_experienciasprofissionaisitem_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='descricao',
        ),
    ]
