# Generated by Django 5.0.5 on 2024-05-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_remove_projetos_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='contato',
            name='localizacao',
            field=models.URLField(blank=True, verbose_name='Localização'),
        ),
    ]
