# Generated by Django 5.0.5 on 2024-05-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_remove_contato_descricao_alter_contato_localizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='contato',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='linkedln',
            field=models.CharField(blank=True, max_length=150, verbose_name='Linkedln'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=150, verbose_name='Telefone'),
        ),
    ]
