# Generated by Django 5.0.5 on 2024-05-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_remove_contato_localizacao_contato_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='cliente',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='data',
            field=models.CharField(blank=True, max_length=30, verbose_name='Data do projeto'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='url',
            field=models.CharField(blank=True, max_length=150, verbose_name='URL do projeto'),
        ),
    ]
