# Generated by Django 5.0.5 on 2024-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_projetos_cliente_projetos_data_projetos_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='url',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL do projeto'),
        ),
    ]
