# Generated by Django 5.0.5 on 2024-05-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_alter_projetos_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Meu Aplicativo'},
        ),
    ]
