# Generated by Django 5.0.5 on 2024-05-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_alter_perfil_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.AlterModelOptions(
            name='educacao',
            options={'verbose_name_plural': 'Sessão educação'},
        ),
        migrations.AlterModelOptions(
            name='experienciasprofissionais',
            options={'verbose_name_plural': 'Sessão experiências'},
        ),
        migrations.AlterModelOptions(
            name='experienciasprofissionaisitem',
            options={'verbose_name_plural': 'Itens experiências'},
        ),
        migrations.AlterModelOptions(
            name='fotosdoprojeto',
            options={'verbose_name_plural': 'Fotos do projeto'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Barra Lateral'},
        ),
        migrations.AlterModelOptions(
            name='projetos',
            options={'verbose_name_plural': 'Sessão Projetos'},
        ),
        migrations.AlterModelOptions(
            name='resumo',
            options={'verbose_name_plural': 'Sessão Resumo'},
        ),
        migrations.AlterModelOptions(
            name='resumoitem',
            options={'verbose_name_plural': 'Itens resumo'},
        ),
        migrations.AlterModelOptions(
            name='sobremim',
            options={'verbose_name_plural': 'Sessão sobre'},
        ),
        migrations.AlterModelOptions(
            name='sobremimitem',
            options={'verbose_name_plural': 'Itens sobre'},
        ),
        migrations.AlterModelOptions(
            name='tecnologiasdedominio',
            options={'verbose_name_plural': 'Sessão tecnologias'},
        ),
    ]
