# Generated by Django 5.0.5 on 2024-05-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_delete_contato_alter_educacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='data',
        ),
        migrations.RemoveField(
            model_name='tecnologiasdedominio',
            name='descricao',
        ),
        migrations.CreateModel(
            name='ProjetoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150, verbose_name='Item')),
                ('itemresposta', models.CharField(max_length=150, verbose_name='Resposta do item')),
                ('projetos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='apps.projetos')),
            ],
            options={
                'verbose_name_plural': 'Itens projeto',
            },
        ),
    ]
