# Generated by Django 5.0.5 on 2024-09-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_remove_projetos_cliente_remove_projetos_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciasprofissionaisitem',
            name='item',
            field=models.TextField(verbose_name='Item'),
        ),
    ]
