# Generated by Django 5.0.5 on 2024-09-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_alter_experienciasprofissionaisitem_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educacao',
        ),
        migrations.RemoveField(
            model_name='experienciasprofissionaisitem',
            name='xp',
        ),
        migrations.RemoveField(
            model_name='fotosdoprojeto',
            name='projetos',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.RemoveField(
            model_name='projetoitem',
            name='projetos',
        ),
        migrations.RemoveField(
            model_name='resumoitem',
            name='resumo',
        ),
        migrations.DeleteModel(
            name='SobreMim',
        ),
        migrations.DeleteModel(
            name='SobreMimItem',
        ),
        migrations.DeleteModel(
            name='TecnologiasDeDominio',
        ),
        migrations.AlterModelOptions(
            name='projetos',
            options={'verbose_name_plural': 'Adicionar Projeto'},
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='url',
        ),
        migrations.AddField(
            model_name='projetos',
            name='titulo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(upload_to='projetos'),
        ),
        migrations.DeleteModel(
            name='ExperienciasProfissionais',
        ),
        migrations.DeleteModel(
            name='ExperienciasProfissionaisItem',
        ),
        migrations.DeleteModel(
            name='FotosDoProjeto',
        ),
        migrations.DeleteModel(
            name='ProjetoItem',
        ),
        migrations.DeleteModel(
            name='Resumo',
        ),
        migrations.DeleteModel(
            name='ResumoItem',
        ),
    ]
