# Generated by Django 5.0.5 on 2024-10-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_delete_educacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='parceiros')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Adicionar Parceiro',
            },
        ),
    ]
