# Generated by Django 5.0.5 on 2024-10-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_parceiros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChavesPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(upload_to='chavepix')),
                ('chave', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Adicionar Chave Pix',
            },
        ),
    ]
