# Generated by Django 5.0.5 on 2024-10-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_eventos'),
        ('apps', '0027_noticias'),
    ]

    operations = [
    ]
