# Generated by Django 5.0.5 on 2024-10-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_merge_0027_eventos_0027_noticias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventos',
        ),
    ]
